import { describe, expect, test } from "vitest";

import { activeCue, cuesForTimestampRange, parseWebVtt } from "./vtt";

const SAMPLE_VTT = `WEBVTT

NOTE generated by the local transcript pipeline

intro
00:00:01.000 --> 00:00:04.500 align:start
We crossed at dawn.

00:00:05.000 --> 00:00:08.000
The border was quiet.

1:02.000 --> 1:05.500
Minutes-only timings are accepted.
`;

describe("parseWebVtt", () => {
  test("parses cue identifiers, settings lines, and both timing formats", () => {
    const cues = parseWebVtt(SAMPLE_VTT);
    expect(cues).toHaveLength(3);
    expect(cues[0]).toEqual({
      id: "intro",
      startMs: 1000,
      endMs: 4500,
      text: "We crossed at dawn.",
    });
    expect(cues[1].id).toBe("cue-1");
    expect(cues[1].startMs).toBe(5000);
    expect(cues[2].startMs).toBe(62_000);
    expect(cues[2].endMs).toBe(65_500);
  });

  test("skips malformed cues without dropping the rest", () => {
    const cues = parseWebVtt(`WEBVTT

00:00:01.000 --> 00:00:02.000
first

broken line

00:00:03.000 --> 00:00:04.000
third
`);
    expect(cues.map((cue) => cue.text)).toEqual(["first", "third"]);
  });
});

describe("cue lookups", () => {
  const cues = parseWebVtt(SAMPLE_VTT);

  test("cuesForTimestampRange returns overlapping cues in order", () => {
    const overlapping = cuesForTimestampRange(cues, 4500, 5500);
    expect(overlapping.map((cue) => cue.text)).toEqual(["The border was quiet."]);
    expect(cuesForTimestampRange(cues, 0, 500)).toEqual([]);
  });

  test("activeCue highlights exactly one cue at a time", () => {
    expect(activeCue(cues, 2000)?.id).toBe("intro");
    expect(activeCue(cues, 4600)).toBeNull();
    expect(activeCue(cues, 62_500)?.text).toBe("Minutes-only timings are accepted.");
  });
});
