import { expect, test, type Page } from "@playwright/test";

/**
 * Task-7 acceptance gate (step 10): the exported palace bundle opens in the
 * public viewer and renders OFFLINE. The public-viewer dev server
 * (127.0.0.1:4174) serves a real `palace-bundle.json` fixture (generated by
 * the shared scene builder, exactly what `writePalaceBundle` writes). The
 * /palace route mounts the shared PalaceSurface read-only. Positive render
 * proof: no error element, non-zero WebGL canvas, and a camera flight changes
 * the rendered pixels. The hostname-filtered network audit runs before and
 * after — nothing leaves the machine.
 */

async function collectExternalRequests(page: Page): Promise<string[]> {
  const external: string[] = [];
  page.on("request", (request) => {
    const url = new URL(request.url());
    if (url.hostname !== "127.0.0.1" && url.hostname !== "localhost") {
      external.push(request.url());
    }
  });
  return external;
}

test("exported palace bundle opens in the public viewer and renders offline", async ({
  page,
}) => {
  const external = await collectExternalRequests(page);

  await page.goto("http://127.0.0.1:4174/palace");

  // The palace surface boots from the exported bundle.
  await expect(page.getByTestId("palace-surface")).toBeVisible({ timeout: 20_000 });

  // Real chambers/objects came from the serialized scene.
  await expect(page.getByTestId("palace-chambers")).toBeVisible();
  await expect(
    page.getByTestId("palace-chambers").locator("li"),
  ).not.toHaveCount(0);
  await expect(page.getByTestId("palace-objects").locator("li")).not.toHaveCount(0);

  // RENDER PROOF 1: no WebGL error banner.
  await expect(page.getByTestId("palace-error")).toHaveCount(0, {
    timeout: 15_000,
  });

  // RENDER PROOF 2: a real WebGL canvas exists and is non-zero-sized.
  const canvas = page.getByTestId("palace-canvas").locator("canvas").first();
  await expect(canvas).toBeVisible();
  const canvasSize = await canvas.evaluate((element) => ({
    width: (element as HTMLCanvasElement).width,
    height: (element as HTMLCanvasElement).height,
  }));
  expect(canvasSize.width).toBeGreaterThan(0);
  expect(canvasSize.height).toBeGreaterThan(0);

  // The first-person camera is live.
  await expect(page.getByTestId("palace-surface")).toHaveAttribute(
    "data-camera",
    /^-?\d+\.\d+,-?\d+\.\d+,-?\d+\.\d+$/,
    { timeout: 15_000 },
  );

  // Read-only viewer: no curation mutations, no export affordance.
  await expect(page.getByTestId("palace-save-state")).toHaveCount(0);
  await expect(page.getByTestId("palace-export-bundle")).toHaveCount(0);

  await page.waitForTimeout(800);

  // Offline gate part 1: zero external requests while rendering the palace.
  expect(external).toEqual([]);

  // RENDER PROOF 3: flying to the next chamber changes the rendered pixels.
  const viewport = page.getByTestId("palace-canvas");
  await viewport.scrollIntoViewIfNeeded();
  const box = await viewport.boundingBox();
  if (!box || box.width < 16 || box.height < 16) {
    throw new Error("palace canvas has no measurable bounding box");
  }
  const screenshot = () =>
    page.screenshot({
      clip: { x: box.x, y: box.y, width: box.width, height: box.height },
    });
  const before = await screenshot();
  const initialCamera = await page
    .getByTestId("palace-surface")
    .getAttribute("data-camera");

  await page.getByTestId("palace-fly-next").click();
  await expect(page.getByTestId("palace-surface")).not.toHaveAttribute(
    "data-camera",
    initialCamera as string,
    { timeout: 10_000 },
  );
  await page.waitForTimeout(900);
  const after = await screenshot();
  expect(before.equals(after)).toBe(false);
  expect(external).toEqual([]);
});
