import { z } from "zod";
export declare const exportAssetSchema: z.ZodObject<{
    nodeId: z.ZodString;
    sourcePath: z.ZodString;
    relativePath: z.ZodString;
    downloadName: z.ZodString;
    mimeType: z.ZodString;
}, z.core.$strip>;
export declare const exportBundleSchema: z.ZodObject<{
    generatedAt: z.ZodString;
    project: z.ZodObject<{
        id: z.ZodString;
        displayName: z.ZodString;
        slug: z.ZodString;
        parentConstellationId: z.ZodNullable<z.ZodString>;
        rootPath: z.ZodString;
        primaryCanvasId: z.ZodString;
        summary: z.ZodDefault<z.ZodString>;
        coverAssetPath: z.ZodNullable<z.ZodString>;
        publishSettings: z.ZodObject<{
            includeResources: z.ZodBoolean;
            mobileSequenceFirst: z.ZodBoolean;
            theme: z.ZodDefault<z.ZodEnum<{
                paper: "paper";
                nocturne: "nocturne";
                ledger: "ledger";
            }>>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, z.core.$strip>;
    canvases: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        projectId: z.ZodString;
        name: z.ZodString;
        kind: z.ZodDefault<z.ZodEnum<{
            primary: "primary";
            subcanvas: "subcanvas";
        }>>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        lastViewport: z.ZodOptional<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
            zoom: z.ZodNumber;
        }, z.core.$strip>>;
    }, z.core.$strip>>;
    nodes: z.ZodArray<z.ZodDiscriminatedUnion<[z.ZodObject<{
        id: z.ZodString;
        canvasId: z.ZodString;
        title: z.ZodString;
        position: z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strip>;
        size: z.ZodObject<{
            width: z.ZodNumber;
            height: z.ZodNumber;
        }, z.core.$strip>;
        summary: z.ZodDefault<z.ZodString>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        type: z.ZodLiteral<"resource">;
        resourceKind: z.ZodEnum<{
            markdown: "markdown";
            text: "text";
            pdf: "pdf";
            image: "image";
            audio: "audio";
            video: "video";
            directory: "directory";
            url: "url";
            binary: "binary";
        }>;
        absolutePath: z.ZodString;
        relativePath: z.ZodString;
        mimeType: z.ZodString;
        fileFingerprint: z.ZodString;
        url: z.ZodOptional<z.ZodString>;
    }, z.core.$strip>, z.ZodObject<{
        id: z.ZodString;
        canvasId: z.ZodString;
        title: z.ZodString;
        position: z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strip>;
        size: z.ZodObject<{
            width: z.ZodNumber;
            height: z.ZodNumber;
        }, z.core.$strip>;
        summary: z.ZodDefault<z.ZodString>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        type: z.ZodLiteral<"note">;
        content: z.ZodString;
        tags: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>, z.ZodObject<{
        id: z.ZodString;
        canvasId: z.ZodString;
        title: z.ZodString;
        position: z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strip>;
        size: z.ZodObject<{
            width: z.ZodNumber;
            height: z.ZodNumber;
        }, z.core.$strip>;
        summary: z.ZodDefault<z.ZodString>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        type: z.ZodLiteral<"group">;
        color: z.ZodString;
        childNodeIds: z.ZodDefault<z.ZodArray<z.ZodString>>;
    }, z.core.$strip>, z.ZodObject<{
        id: z.ZodString;
        canvasId: z.ZodString;
        title: z.ZodString;
        position: z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
        }, z.core.$strip>;
        size: z.ZodObject<{
            width: z.ZodNumber;
            height: z.ZodNumber;
        }, z.core.$strip>;
        summary: z.ZodDefault<z.ZodString>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
        type: z.ZodLiteral<"portal">;
        targetCanvasId: z.ZodString;
    }, z.core.$strip>], "type">>;
    edges: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        canvasId: z.ZodString;
        sourceNodeId: z.ZodString;
        targetNodeId: z.ZodString;
        relationKind: z.ZodString;
        directionality: z.ZodEnum<{
            none: "none";
            forward: "forward";
            backward: "backward";
            bidirectional: "bidirectional";
        }>;
        label: z.ZodDefault<z.ZodString>;
        note: z.ZodDefault<z.ZodString>;
        style: z.ZodObject<{
            stroke: z.ZodString;
            width: z.ZodNumber;
            dashed: z.ZodDefault<z.ZodBoolean>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, z.core.$strip>>;
    sequences: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        projectId: z.ZodString;
        canvasId: z.ZodString;
        name: z.ZodString;
        kind: z.ZodEnum<{
            storyboard: "storyboard";
            historical: "historical";
            logical: "logical";
            research: "research";
            presentation: "presentation";
        }>;
        description: z.ZodDefault<z.ZodString>;
        published: z.ZodBoolean;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, z.core.$strip>>;
    sequenceSteps: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        sequenceId: z.ZodString;
        position: z.ZodNumber;
        targetType: z.ZodEnum<{
            node: "node";
            edge: "edge";
        }>;
        targetId: z.ZodString;
        caption: z.ZodDefault<z.ZodString>;
        viewport: z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
            zoom: z.ZodNumber;
        }, z.core.$strip>;
        transitionHint: z.ZodDefault<z.ZodEnum<{
            cut: "cut";
            ease: "ease";
            spotlight: "spotlight";
        }>>;
    }, z.core.$strip>>;
    annotations: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        canvasId: z.ZodString;
        annotationType: z.ZodEnum<{
            stroke: "stroke";
            highlight: "highlight";
            arrow: "arrow";
            callout: "callout";
        }>;
        points: z.ZodArray<z.ZodObject<{
            x: z.ZodNumber;
            y: z.ZodNumber;
            pressure: z.ZodOptional<z.ZodNumber>;
        }, z.core.$strip>>;
        style: z.ZodObject<{
            color: z.ZodString;
            width: z.ZodNumber;
            opacity: z.ZodNumber;
        }, z.core.$strip>;
        text: z.ZodOptional<z.ZodString>;
        bounds: z.ZodObject<{
            position: z.ZodObject<{
                x: z.ZodNumber;
                y: z.ZodNumber;
            }, z.core.$strip>;
            size: z.ZodObject<{
                width: z.ZodNumber;
                height: z.ZodNumber;
            }, z.core.$strip>;
        }, z.core.$strip>;
        createdAt: z.ZodString;
        updatedAt: z.ZodString;
    }, z.core.$strip>>;
    assets: z.ZodDefault<z.ZodArray<z.ZodObject<{
        nodeId: z.ZodString;
        sourcePath: z.ZodString;
        relativePath: z.ZodString;
        downloadName: z.ZodString;
        mimeType: z.ZodString;
    }, z.core.$strip>>>;
}, z.core.$strip>;
export type ExportAsset = z.infer<typeof exportAssetSchema>;
export type ExportBundle = z.infer<typeof exportBundleSchema>;
